server:

  tomcat:
    max-threads: 30
    uri-encoding: utf-8
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xve?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234567
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSourceC3P0Adapter
  devtools:
    restart:
      enable: true  #热部署生效
      additonal-paths: src/main/java
      exclude: static/**

mybatis:
  type-aliases-package: com.myeval.entity
  mapper-locations: classpath:mapper/*.xml


